services:
  mariadb:
    container_name: mariadb_erpnpc
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
    ports:
      - '4002:3306'
  # Php 8.3
  php:  
    container_name: php_erpnpc
    build:
      context: .
      
      dockerfile: dockerfilephp
    depends_on:
      - mariadb
    volumes:
      - './:/var/www/html'
    ports:
      - '4000:80'
  jasperreports:
    container_name: jasperreports_erpnpc
    image: docker.io/bitnami/jasperreports:8
    ports:
      #- '80:8080'
      - '4001:8080'
    volumes:
      - './jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_DATABASE_HOST=172.17.0.1
      - JASPERREPORTS_DATABASE_PORT_NUMBER=4002
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
# volumes:
#   mariadb_data:
#     driver: local
#   jasperreports_data:
#     driver: local
